### ISSUE TITLE
智能家居怎么拼接网址

### ISSUE THREAD

**Issue by haoxiongqin** [rokid/community#12]
关于智能家居接入加入的网址是怎么拼接的呢，，在https://s.rokidcdn.com/homebase/tob/index.html#/homes/index?theme=default 后面需要拼接什么？

**Comment by maxbbn** [comment]
实现对应的 bridge 接口即可， 后面不需要拼接额外参数

**Comment by maxbbn** [comment]
@haoxiongqin 问题关闭， 如有问题可以再打开
